inputs = [
    [{ x = "314573" }, { x = "222822" }, { x = "104858" }, { x = "13107" }],
    [{ x = "425984" }, { x = "196608" }, { x = "340787" }, { x = "131072" }],
    [{ x = "425984" }, { x = "196608" }, { x = "360448" }, { x = "117965" }],
    [{ x = "321126" }, { x = "203162" }, { x = "98304" }, { x = "13107" }],
    [{ x = "353894" }, { x = "255590" }, { x = "85197" }, { x = "26214" }],
    [{ x = "380109" }, { x = "170394" }, { x = "262144" }, { x = "78643" }],
    [{ x = "334234" }, { x = "163840" }, { x = "196608" }, { x = "72090" }],
    [{ x = "412877" }, { x = "176947" }, { x = "321126" }, { x = "117965" }],
    [{ x = "373555" }, { x = "288358" }, { x = "98304" }, { x = "26214" }],
    [{ x = "517734" }, { x = "249037" }, { x = "419430" }, { x = "131072" }],
    [{ x = "406323" }, { x = "190054" }, { x = "281805" }, { x = "85197" }],
    [{ x = "288358" }, { x = "196608" }, { x = "85197" }, { x = "13107" }],
    [{ x = "399770" }, { x = "183501" }, { x = "262144" }, { x = "85197" }],
    [{ x = "321126" }, { x = "157286" }, { x = "216269" }, { x = "65536" }],
    [{ x = "340787" }, { x = "222822" }, { x = "91750" }, { x = "13107" }],
    [{ x = "406323" }, { x = "144179" }, { x = "294912" }, { x = "98304" }],
    [{ x = "353894" }, { x = "255590" }, { x = "111411" }, { x = "26214" }],
    [{ x = "308019" }, { x = "209715" }, { x = "85197" }, { x = "13107" }],
    [{ x = "360448" }, { x = "229376" }, { x = "85197" }, { x = "13107" }],
    [{ x = "308019" }, { x = "209715" }, { x = "85197" }, { x = "13107" }],
    [{ x = "373555" }, { x = "249037" }, { x = "111411" }, { x = "19661" }],
    [{ x = "327680" }, { x = "131072" }, { x = "229376" }, { x = "65536" }],
    [{ x = "360448" }, { x = "157286" }, { x = "249037" }, { x = "72090" }],
    [{ x = "367002" }, { x = "190054" }, { x = "235930" }, { x = "85197" }],
    [{ x = "393216" }, { x = "190054" }, { x = "294912" }, { x = "98304" }],
    [{ x = "399770" }, { x = "170394" }, { x = "367002" }, { x = "91750" }],
    [{ x = "452198" }, { x = "209715" }, { x = "373555" }, { x = "150733" }],
    [{ x = "373555" }, { x = "249037" }, { x = "111411" }, { x = "19661" }],
    [{ x = "386662" }, { x = "196608" }, { x = "275251" }, { x = "98304" }],
    [{ x = "308019" }, { x = "209715" }, { x = "85197" }, { x = "13107" }],
    [{ x = "504627" }, { x = "170394" }, { x = "452198" }, { x = "150733" }],
    [{ x = "327680" }, { x = "222822" }, { x = "104858" }, { x = "26214" }],
    [{ x = "373555" }, { x = "183501" }, { x = "294912" }, { x = "85197" }],
    [{ x = "412877" }, { x = "216269" }, { x = "308019" }, { x = "104858" }],
    [{ x = "425984" }, { x = "209715" }, { x = "334234" }, { x = "131072" }],
    [{ x = "281805" }, { x = "196608" }, { x = "72090" }, { x = "6554" }],
    [{ x = "373555" }, { x = "183501" }, { x = "268698" }, { x = "85197" }],
    [{ x = "412877" }, { x = "222822" }, { x = "367002" }, { x = "157286" }],
    [{ x = "504627" }, { x = "170394" }, { x = "452198" }, { x = "150733" }],
    [{ x = "406323" }, { x = "222822" }, { x = "353894" }, { x = "150733" }],
    [{ x = "301466" }, { x = "235930" }, { x = "65536" }, { x = "13107" }],
    [{ x = "498074" }, { x = "196608" }, { x = "432538" }, { x = "137626" }],
    [{ x = "399770" }, { x = "190054" }, { x = "308019" }, { x = "91750" }],
    [{ x = "484966" }, { x = "183501" }, { x = "399770" }, { x = "124518" }],
    [{ x = "419430" }, { x = "209715" }, { x = "347341" }, { x = "150733" }],
    [{ x = "327680" }, { x = "235930" }, { x = "91750" }, { x = "13107" }],
    [{ x = "393216" }, { x = "176947" }, { x = "334234" }, { x = "104858" }],
    [{ x = "327680" }, { x = "209715" }, { x = "78643" }, { x = "13107" }],
    [{ x = "327680" }, { x = "150733" }, { x = "216269" }, { x = "65536" }],
    [{ x = "360448" }, { x = "150733" }, { x = "262144" }, { x = "85197" }]
]

labels = [
    [{ x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "65536" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }],
    [{ x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "65536" }],
    [{ x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }]
]